In [ ]:
### CONVOLUTION 

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def convolution(image, kernel):
  image_h = image.shape[0]
  image_w = image.shape[1]
    
  kernel_h = kernel.shape[0]
  kernel_w = kernel.shape[1]

  h = kernel_h // 2
  w = kernel_w // 2

  ## Padding the image 
  if(len(image.shape) == 3):
      image_pad = np.pad(image, pad_width=(
          (h,h), (w,w),
          (0,0)), mode='constant', 
          constant_values=0).astype(np.float32)

  elif(len(image.shape) == 2):
      image_pad = np.pad(image, pad_width=(
          (h,h),(w,w)), mode='constant', 
          constant_values=0).astype(np.float32)
    
  image_conv = np.zeros(image_pad.shape)

  #Performing the convolution  
  for i in range(h, image_pad.shape[0]-h):
      for j in range(w, image_pad.shape[1]-w):
          x = image_pad[i-h:i-h+kernel_h, j-w:j-w+kernel_w]
          x = x.flatten()*kernel.flatten()
          image_conv[i][j] = x.sum()
  h_end = -h
  w_end = -w
  
  if(h == 0):
      return image_conv[h:,w:w_end]
  if(w == 0):
      return image_conv[h:h_end,w:]

  return image_conv[h:h_end,w:w_end]

### APPLYING THE GAUSSIAN FILTER

def GaussianFilter(image, sigma):
    image = Image.open(image).convert('L')
    image.save('/gray.jpg')
    image = np.asarray(image)
    filter_size = 2 * int(4 * sigma + 0.5) + 1
    #filter_size = 
    #Modify as per noise removal requirement
    #Currently setting 1
    #Don't want to end up blurring too many edges

    gaussian_filter = np.zeros((filter_size, filter_size), np.float32)
    m = filter_size//2
    n = filter_size//2
    
    for x in range(-m, m+1):
        for y in range(-n, n+1):
            x1 = 2*np.pi*(sigma**2)
            x2 = np.exp(-(x**2 + y**2)/(2* sigma**2))
            gaussian_filter[x+m, y+n] = (1/x1)*x2
    
    im_filtered = np.zeros_like(image, dtype=np.float32)
    
    #for c in range(3):
     #   im_filtered[:, :, c] = convolution(image[:, :, c], gaussian_filter)

    im_filtered[:,:] = convolution(image[:,:],gaussian_filter)
    
    print("DONE!")
    out = Image.fromarray(im_filtered.astype(np.uint8))
    out.save('/output.jpg')
    
    return (im_filtered.astype(np.uint8))

GaussianFilter("test.jpg",1.5)


DONE!


array([[ 99, 133, 152, ..., 148, 131,  98],
       [132, 178, 203, ..., 198, 176, 131],
       [149, 201, 229, ..., 224, 198, 148],
       ...,
       [148, 198, 224, ..., 224, 198, 148],
       [131, 176, 198, ..., 198, 176, 131],
       [ 98, 131, 148, ..., 148, 131,  98]], dtype=uint8)

In [ ]:
# Below are 3 different hard-coded high pass filters

# hpf1 = np.zeros((3, 3), np.float32)

# for x in range(3):
#     for y in range(3):
#         if ((x == 1) and (y == 1)):
#             hpf1[x, y] = 7.0/8.0
#         else:
#           hpf1[x, y] = -1.0/8.0
      
hpf1 = np.zeros((3, 3), np.float32)

hpf1[0, 0] = 0
hpf1[0, 2] = 0
hpf1[2, 0] = 0
hpf1[2, 2] = 0
hpf1[0, 1] = -1
hpf1[1, 0] = -1
hpf1[2, 1] = -1
hpf1[1, 2] = -1
hpf1[1, 1] = 4


hpf2 = np.zeros((3, 3), np.float32)

for x in range(3):
    for y in range(3):
        if ((x == 1) and (y == 1)):
            hpf2[x, y] = 8.0/9.0
        else:
          hpf2[x, y] = -1.0/9.0
        
hpf4 = np.zeros((4, 4), np.float32)

for x in range(4):
    for y in range(4):
        if ((x == 1) and (y == 1)) or ((x == 1) and (y == 2)) or ((x == 2) and (y == 1)) or ((x == 2) and (y == 2)):
            hpf4[x, y] = 3.0/16.0
        else:
          hpf4[x, y] = -1.0/16.0


  

hpf3 = np.zeros((5, 5), np.float32)

hpf3[0, 0] = 0
hpf3[0, 4] = 0
hpf3[4, 0] = 0
hpf3[4, 4] = 0
hpf3[0, 1] = -1
hpf3[0, 2] = -1
hpf3[0, 3] = -1
hpf3[1, 0] = -1
hpf3[1, 4] = -1
hpf3[2, 0] = -1
hpf3[2, 4] = -1
hpf3[3, 0] = -1
hpf3[3, 4] = -1
hpf3[4, 1] = -1
hpf3[4, 2] = -1
hpf3[4, 3] = -1
hpf3[1, 1] = 2
hpf3[1, 3] = 2
hpf3[3, 1] = 2
hpf3[3, 3] = 2
hpf3[1, 2] = -3
hpf3[2, 1] = -3
hpf3[2, 3] = -3
hpf3[3, 2] = -3
hpf3[2, 2] = 16

print(hpf3)

# hpf4 = np.zeros((4, 4), np.float32)

# for x in range(4):
#     for y in range(4):
#         if ((x == 1) and (y == 1)) or ((x == 1) and (y == 2)) or ((x == 2) and (y == 1)) or ((x == 2) and (y == 2)):
#             hpf4[x, y] = 3
#         else:
#           hpf4[x, y] = -1

# print(hpf4)
# -1 -1 -1 -1
# -1 3  3  -1
# -1 3  3  -1
# -1 -1 -1 -1

        

[[ 0. -1. -1. -1.  0.]
 [-1.  2. -3.  2. -1.]
 [-1. -3. 16. -3. -1.]
 [-1.  2. -3.  2. -1.]
 [ 0. -1. -1. -1.  0.]]


In [ ]:
# Trying out with High Pass filters on the gaussian filtered image

def HighPassFiltering(image, filter, output_file_name):

    output_array = np.zeros_like(image, dtype=np.float32)
    output_array = convolution(image[:,:],filter)

    print("DONE!")
    output = Image.fromarray(output_array.astype(np.uint8))
    output.save(output_file_name)
    
    return (output_array.astype(np.uint8))


gaussian_image = GaussianFilter("test.jpg",1.5)

high_pass_test_1 = HighPassFiltering(gaussian_image, hpf1/9.0, '/high_pass_test_1.jpg')
high_pass_test_2 = HighPassFiltering(gaussian_image, hpf2, '/high_pass_test_2.jpg')
high_pass_test_3 = HighPassFiltering(gaussian_image, hpf3/25.0, '/high_pass_test_3.jpg')
high_pass_test_4 = HighPassFiltering(gaussian_image, hpf4, '/high_pass_test_4.jpg')
# high_pass_test_5 = HighPassFiltering(gaussian_image, hpf5/9.0, '/high_pass_test_5.jpg')


DONE!
DONE!
DONE!
DONE!
DONE!


In [ ]:
# Trying with direct application of high pass filters

def DirectHighPass(image, filter, output_image):

    image = Image.open(image)
    img_data = image.getdata()
    lst=[]
    for i in img_data:
        lst.append(i[0]*0.2125+i[1]*0.7174+i[2]*0.0721)
    image = Image.new("L", image.size)
    image.putdata(lst)
    image.convert()
    image.save('/gray.jpg')
    image = np.asarray(image)
    
    output_array = np.zeros_like(image, dtype=np.float32)
    output_array[:,:] = convolution(image[:,:],filter)
    
    print("DONE!")
    out = Image.fromarray(output_array.astype(np.uint8))
    out.save(output_image)
    
    return (output_array.astype(np.uint8))

direct_high_pass_1 = DirectHighPass('test.jpg', hpf1/9.0, '/direct_high_pass_1.jpg')
direct_high_pass_2 = DirectHighPass('test.jpg', hpf2, '/direct_high_pass_2.jpg')
direct_high_pass_3 = DirectHighPass('test.jpg', hpf3/25.0, '/direct_high_pass_3.jpg')
direct_high_pass_4 = DirectHighPass('test.jpg', hpf4, '/direct_high_pass_4.jpg')



DONE!
DONE!
DONE!
DONE!


In [ ]:
###### REFERENCES 

#https://www2.geog.soton.ac.uk/users/trevesr/obs/rseo/high_pass_filters.html
#https://www.l3harrisgeospatial.com/docs/highpassfilter.html